<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>isaac_ros_perception_demo</name>
  <version>0.1.0</version>
  <description>Chapter 15 C++ AprilTag pose logger demo (Isaac ROS)</description>
  <maintainer email="you@example.com">your-name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>isaac_ros_apriltag_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
